# <span style="color:darkblue"> Lecture 3 Exercises </span>



## Short Questions

<font size = "5">

1. What is a codebook?
2. How you define a missing value in Python?
2. What is chaining?

In [ ]:
# Write your answers here as comments

# 1. A codebook is the place where you can check the names, types, and descriptions of variables.
# 2. Use np.nan.
# 3. Putting many commands together using pipe (.).

## Long Questions

<font size = "5">

Import the libraries "numpy" and "pandas"

In [3]:
# Write your own code

import numpy as np
import pandas as pd

<font size = "5">

(a) Replace values from intervals

<font size = "3">

- Import the dataset "data_raw/students.csv" to a new object "students"
- Use "pd.cut()" to assign the column "numericgrade" to a letter grade <br>
using the following table

<img src="figures/grading_scale.png" alt="drawing" width="600"/>

In [6]:
# Write your own code

students = pd.read_csv("data_raw/students.csv")

bins = [-1, 54, 59, 64, 69, 74, 79, 82, 86, 92, 100]
labels = ["F", "D", "C-", "C", "C+",
          "B-", "B", "B+", "A-", "A"]

students["lettergrade"] = pd.cut(students["numericgrade"],
                                 bins = bins,
                                 right = True,
                                 labels = labels)

<font size = "5">

For questions (b)-(e) use "results.csv", <br>
a dataset on competitive car racing

Import the dataset "data/raw_results.csv" to <br>
 a new object "results"

<font size = "5">

(b) Check column types

<font size = "3">

- View the dataset
- Use the function "results.dtypes" to get the column types
- Search for the "results" table in "codebook/f1_codebook.pdf".
- Does the type of the "milliseconds" column agree with the codebook? <br>
i.e. is it an integer, float, or string/object?


HINT: See Lectures 13 and 14 for how to interpret the codebook

In [ ]:
# Write your own code

results = pd.read_csv("data_raw/results.csv")

results.dtypes

# No, it does not. It is an object in the dataset 
# while it is integer in the codebook.

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

<font size = "5">

(c) Clean a column

<font size = "3">

- Import the dataset "data_raw/results.csv" to a new object "results"
- Our goal is to replace any string values in the column "milliseconds" <br>
to missing values (NaNs) and covert to numeric
- To do so, go to Lecture 13 and follow the setups under the headings
    - "Extract list of non-numeric values"
    - "Replace certain values"
    - "Convert column to numeric"

HINT: substitute "milliseconds" instead of "alt", <br>
and the dataset "results" instead of "circuits"

In [8]:
# Write your own code

non_num = results.query("milliseconds.str.isnumeric() == False")
non_num_unique = pd.unique(non_num["milliseconds"])

In [10]:
old_list = ["\\N"]
new_list = [np.nan]

results["milliseconds"] = results["milliseconds"].replace(old_list, new_list)

results["milliseconds"].dtypes

dtype('O')

<font size = "5">

(d) Groupby + Aggregate

<font size = "3">

- Compute the mean and standard deviation of "laps", <br>
grouping by "constructorId". Store the new dataset <br>
as "results_agg"
- Sort the aggregate dataset in decending <br>
order of mean laps using ".sort_values()"

HINT: See Lecture 14 <br>

In [12]:
# Write your own code

results_agg = (results.groupby("constructorId")
                      .agg(mean_laps = ('laps', 'mean'))
                      .sort_values(by = "mean_laps", ascending = False))

results_agg

                mean_laps
constructorId
149            198.500000
112            197.000000
109            184.285714
119            178.666667
108            163.764706
...                   ...
93               0.000000
61               0.000000
137              0.000000
91               0.000000
74               0.000000

[210 rows x 1 columns]

<font size = "5" >

(e) Query + Groupby + Aggregate

<font size = "3">

- Use ".query()" to subset observations with <br>
'race_id >= 200'
- Compute the mean and standard deviation of "laps", <br>
grouping by "constructorId". Store the new dataset <br>
as "results_agg"

Hint: See Lecture 11 (to refresh ".query()") and <br>
Lecture 14 for how to combine it with ".groupby()"

In [14]:
# Write your own code

results_agg2 = (results.query("raceId >= 200")
                       .groupby("constructorId")
                       .agg(mean_laps = ('laps', 'mean'),
                            std_laps = ('laps', 'std')))

results_agg2

               mean_laps   std_laps
constructorId
1              50.093510  23.147774
3              51.349621  21.064902
4              46.396450  22.565290
5              51.787879  18.281774
6              50.305798  25.953854
...                  ...        ...
209            52.282051  19.522147
210            51.434028  19.915741
211            54.684211  17.680279
213            52.393443  19.883361
214            54.204545  17.951505

[201 rows x 2 columns]


<font size = "5">

(f) Replace the values of a column

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Replace the values "E" with 11 in the column "positionText"
- Create a new column "positionNumeric" that converts <br>
the modified "positionText" column from string to numeric <br>
using ```pd.to_numeric()```

In [8]:
# Write your own code

standing = pd.read_csv("data_raw/constructor_standings.csv")

old_list = ["E"]
new_list = [11]

standing["positionText"] = standing["positionText"].replace(old_list, new_list)

standing["positionNumeric"] = pd.to_numeric(standing["positionText"])

<font size = "5">

(g) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1970","1971-1990","1991-2005", "2006-2020", "2020-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [5]:
# Write your own code

race = pd.read_csv("data_raw/races.csv")

year_bins = [1950, 1970, 1990, 2005, 2020, float("inf")]
year_labels = ["1950-1970",
               "1971-1990",
               "1991-2005",
               "2006-2020",
               "2020-onwards"]

race["year_brackets"] = pd.cut(race["year"],
                               bins = year_bins,
                               right = True,
                               include_lowest = True,
                               labels = year_labels)

<font size = "5">

(h) Aggregate and query

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Subset the observations for 'raceId == 10' using ```.query()```
- Obtain the sum of "points" by "constructorId" <br> 
(the team) using ``` .groupby().agg() ```
- Subset the teams with a sum of points $\ge 50$
- Store the results of all these operations in a dataframe <br>
```constructor_standings_agg ```

In [ ]:
# Write your own code

constructor_standings_agg = (standing.query("raceId == 10")
                                     .groupby("constructorId")
                                     .agg(points_sum = ('points', 'sum'))
                                     .query("points_sum >= 50"))

<font size = "5">

(i) Aggregate and sort

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Obtain the sum of "points" by "constructorId" <br> 
(the team) using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the sum of points using ``` .sort_values() ```

In [11]:
# Write your own code

standing.groupby("constructorId").agg(points_sum = ('points', 'sum')).sort_values(by = "points_sum", ascending = False)

               points_sum
constructorId
6                 90204.0
131               71808.5
9                 64986.5
1                 57188.5
3                 32093.5
...                   ...
93                    0.0
92                    0.0
90                    0.0
89                    0.0
91                    0.0

[159 rows x 1 columns]

<font size = "5">

(j) Rename column

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Rename the column "wins" to "wins_constructor"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>

In [ ]:
# Write your own code

standing.rename(columns={
    "wins": "wins_constrcutor"
})

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins_constrcutor,positionNumeric
0,1,18,1,14.0,1,1,1,1
1,2,18,2,8.0,3,3,0,3
2,3,18,3,9.0,2,2,0,2
3,4,18,4,5.0,4,4,0,4
4,5,18,5,2.0,5,5,0,5
...,...,...,...,...,...,...,...,...
12936,28408,1098,210,0.0,6,6,0,6
12937,28409,1098,1,0.0,7,7,0,7
12938,28410,1098,131,0.0,8,8,0,8
12939,28411,1098,9,0.0,9,9,0,9
12940,28412,1098,3,0.0,10,10,0,10

<font size = "5">

(k) Merge dataset

<font size = "3">

- Import the "data_raw/constructor_standings.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"constructor_standings" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "nationality" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [14]:
# Write your own code

constructor = pd.read_csv("data_raw/constructors.csv")

merged_constructor_data = pd.merge(standing,
                                   constructor[["nationality", "constructorId"]],
                                   how = "left",
                                   on = "constructorId")

<font size = "5">

(l) Formatted results table

<font size = "3">

-  For the dataset you computed above construct a \
descriptive statistics table
- Round the numbers and change the column names to something \
more interpretable

In [27]:
# Write your own code

descriptive = (merged_constructor_data.groupby("nationality", as_index = False)
                                       .agg(mean_points = ("points", "mean"))
                                       .sort_values(by = "mean_points",
                                                    ascending = False)
                                       .rename(columns = {
                                           "nationality": "Nationality of the Constructor",
                                           "mean_points": "Average Points"
                                           }).style.format({
                                               "Average Points": "{:,.2f}"
                                               }).hide(axis = "index").set_caption("Average Points by Nationality of the Constructor"))

descriptive